# Generated by Django 4.2.3 on 2023-07-07 17:33

import blog.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=260, null=True)),
                ('topic', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='blog_md/', validators=[blog.utils.file_validate])),
                ('is_approved', models.BooleanField(default=False)),
                ('mail', models.EmailField(max_length=254, validators=[blog.utils.mail_validation])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
