# Generated by Django 4.2.3 on 2023-07-21 05:19

import blog.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=260, null=True)),
                ('topic', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(upload_to='thumbnails', validators=[blog.utils.file_img_validate])),
                ('author', models.CharField(max_length=255)),
                ('is_approved', models.BooleanField(default=False)),
                ('mail', models.EmailField(max_length=254, validators=[blog.utils.mail_validation])),
                ('file', models.FileField(upload_to=blog.utils.get_upload_folder, validators=[blog.utils.file_md_validate])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShortNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=512)),
                ('content', models.TextField()),
                ('issued_by', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
