# Generated by Django 4.2.3 on 2023-07-08 04:39

import blog.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=512)),
                ('content', models.TextField()),
                ('issued_by', models.CharField(max_length=255)),
                ('desgination', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='file',
            field=models.FileField(upload_to=blog.utils.get_upload_folder, validators=[blog.utils.file_validate]),
        ),
    ]
