# Generated by Django 4.2.3 on 2023-07-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.CharField(default='Hello this is test desc', max_length=510),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shortnotice',
            name='tag',
            field=models.CharField(choices=[('event', 'Event'), ('news', 'News')], default='event', max_length=255),
            preserve_default=False,
        ),
    ]
