# Generated by Django 4.2.3 on 2023-07-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_description_shortnotice_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('news_and_announcement', 'News And Announcement'), ('event', 'Event'), ('general', 'General'), ('academics', 'Academics'), ('parents_resource', 'Parents Resource'), ('career', 'Career'), ('acheivements', 'Achievements'), ('school_policies_guidelines', 'School Policies And Guidelines'), ('health_wellness', 'Health and Wellness'), ('technology', 'Technology'), ('arts', 'Arts'), ('science', 'Science')], default='news', max_length=255),
            preserve_default=False,
        ),
    ]
