# Generated by Django 4.2.3 on 2023-07-08 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_shortnotice_alter_blog_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortnotice',
            old_name='desgination',
            new_name='designation',
        ),
    ]
