# Generated by Django 4.2.3 on 2023-07-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
